version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: medibox_db
    expose:
      - "3307"
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: medibox
      MYSQL_ROOT_USER: root
      MYSQL_USER: codeidea
      MYSQL_PASSWORD: code0809_
      MYSQL_ROOT_PASSWORD: botbinoo1q2w3e!
    command:
      - --character-set-server=utf16
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
  medibox_php:
    image: php:7.3-fpm
    container_name: medibox_php
    depends_on:
      - db
    expose:
      - "9000"
    volumes:
      - ./source:/source
    restart: always
  web:
    container_name: medibox_nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    volumes:
      - ./source:/source
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - medibox_php
    restart: always
volumes:
  mysql-data: